name: cylc-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - ansimarkup >=1.0.0
  - colorama >=0.4,<0.5
  - click >=7.0
  - cryptography
  - graphene >=2.1,<3
  - jinja2 ==2.11.0,<2.12
  - metomi-isodatetime ==1!2.0.1
  - protobuf ==3.12.1
  - pyasn1
  - python
  - pyzmq >=18.1.0,<18.2.0
  - psutil >=5.6.0
  - urwid >=2.0,<2.1
  #- empy >=3.3,<3.4
  #- pandas >=0.25.0,<0.26
  #- pympler
  #- matplotlib-base
  #- rx >=1.6,<2 # TODO: https://github.com/conda-forge/cylc-feedstock/pull/3#issuecomment-660716268
