
# THIS FILE IS PART OF THE CYLC WORKFLOW ENGINE.
# Copyright (C) NIWA & British Crown (Met Office) & Contributors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""Mapping of Sphinx "objects" to documentation URLs.

These URLs are for use in warnings and error messages.

This file is autogenerated by etc/bin/docs.py, to register new "objects"
please add them to etc/bin/docs.py and rebuild this file.

Use "from _ import _" rather than "import _" to import references from this
file so that they result in import errors if the reference is removed.

"""

CYLC_SETTING_FLOW_CYLC_SCHEDULER_ALLOW_IMPLICIT_TASKS = (
    "https://cylc.github.io/cylc-doc/latest/html/reference/config/workflow.html#flow.cylc[scheduler]allow implicit tasks"
)
STD_LABEL_CYLC_7_COMPAT_MODE = (
    "https://cylc.github.io/cylc-doc/latest/html/7-to-8/major-changes/compatibility-mode.html#cylc-7-compat-mode"
)
STD_LABEL_MAJORCHANGESPLATFORMS = (
    "https://cylc.github.io/cylc-doc/latest/html/7-to-8/major-changes/platforms.html#majorchangesplatforms"
)
