name: protobuf

on:
  pull_request:
  workflow_dispatch:

jobs:
  protobuf:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install bufbuild/buf/buf
          buf --help

      - name: Lint
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          buf lint cylc/flow/data_messages.proto

      - name: Build
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          buf build cylc/flow/data_messages.proto
