name: conda build

on:
  pull_request:
    paths:
      - 'conda-environment.yml'
      - '.github/workflows/test_conda-build.yml'
  schedule:
    - cron: '17 22 * * 6'
  workflow_dispatch:

jobs:
  test_conda_install:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout cylc-flow
        uses: actions/checkout@v2

      - name: build conda env
        run: |
          # The appended lines make sure that we actually build with Cylc too:
          echo "  - pip" >> conda-evironment.yml
          echo "  - pip": >> conda-environment.yml
          echo "    - ." >> conda-environment.yml
          cat conda-environment.yml
          conda env create \
            -f conda-environment.yml \
            --prefix cylc-dev
          . /usr/share/miniconda/etc/profile.d/conda.sh
          conda run --prefix cylc-dev cylc version --long

      - name: check for activate scripts
        run: |
          # locate all activate scripts
          find ./cylc-dev/ -name "activate.d" | tee > activates.txt
          # ignore the conda activate script itself
          sed -i '/cylc-dev\/etc\/conda\/activate.d/d' activates.txt
          # check to make sure no packages have contributed new activate scripts
          # (we rely on having a conda activate-less environment)
          if [[ $(cat activates.txt | wc -l) -ne 0 ]]; then
              echo 'Found activate scripts in installation.' >&2
              cat activates.txt >&2
              exit 1
          fi
