name: dns test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        try: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
    steps:
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: hostname
        run: |
          for opt in '-A' '-d' '-f' '-y'; do
              echo "hostname $opt: $(hostname $opt)"
          done
      - name: python.socket
        shell: python
        run: |
          import socket
          for expr in (
              'socket.gethostname()',
              'socket.getfqdn()',
              'socket.gethostbyname(socket.gethostname())',
              'socket.gethostbyname_ex(socket.gethostname())',
              'socket.gethostbyname(socket.getfqdn())',
              'socket.gethostbyname_ex(socket.getfqdn())'
          ):
              print(f'{expr:50}: {eval(expr)}')
