name: fast tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.7', '3.8', '3.9']
        include:
          - os: 'macos-latest'
            python-version: '3.7'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Brew Install
        if: startsWith(matrix.os, 'macos')
        run: |
          brew update
          brew install shellcheck sqlite3

      - name: Apt-Get Install
        if: endsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck sqlite3

      - name: Install
        run: |
          pip install ."[all]"

      - name: Style
        run: |
          pycodestyle
          flake8
          etc/bin/shellchecker

      - name: Doctests
        run: |
          pytest --cov --cov-append -n 5 cylc/flow

      - name: Unit Tests
        run: |
          pytest --cov --cov-append -n 5 tests/unit

      - name: Integration Tests
        run: |
          pytest --cov --cov-append -n 5 tests/integration

      - name: Coverage
        run: |
          coverage report
          bash <(curl -s https://codecov.io/bash)
